version: '3.8'

services:
  
  backend:
    build:
      context: ./ResumeBuilderBackend
    ports:
      - "4292:4292"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - FRONT_END=${FRONT_END}
      - OPENAI_KEY=${OPENAI_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
  
  frontend:
    build:
      context: ./ResumeBuilderAngular
    ports:
      - "80:80"